# Generated by Django 6.1.1 on 2026-09-29 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Traveller categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('region', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], default='domestic', max_length=15)),
                ('state_or_country', models.CharField(blank=True, help_text='State (domestic) or country (international)', max_length=80)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('image', models.ImageField(blank=True, upload_to='destinations/')),
                ('is_popular', models.BooleanField(default=False, help_text="Show in 'Popular places' on the home page")),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OptionalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('adult_price', models.PositiveIntegerField(default=0)),
                ('child_price', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Optional experience',
                'verbose_name_plural': 'Optional experiences',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Flamingo Travels', max_length=80)),
                ('tagline', models.CharField(default='Journeys that feel like golden hour', max_length=160)),
                ('logo', models.ImageField(blank=True, help_text='Upload your logo (PNG with transparent background works best).', upload_to='brand/')),
                ('phone', models.CharField(default='+91 90000 00000', max_length=30)),
                ('whatsapp_number', models.CharField(default='919000000000', help_text='Digits only with country code, e.g. 919876543210', max_length=20)),
                ('email', models.EmailField(default='hello@example.com', help_text='Enquiries are also sent to this address.', max_length=254)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('hero_title', models.CharField(default='Chase the sunset, anywhere in the world', max_length=140)),
                ('hero_subtitle', models.CharField(default='100+ handcrafted domestic and international holidays with transparent pricing.', max_length=240)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, help_text='An emoji, e.g. 🏖️', max_length=8)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('adults', models.PositiveSmallIntegerField(default=2)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('hotel_tier', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('premium', 'Premium')], default='standard', max_length=10)),
                ('departure_city', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField(blank=True)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('price_breakdown', models.JSONField(blank=True, default=dict, help_text='Snapshot of the calculator at enquiry time')),
                ('status', models.CharField(choices=[('new', 'New enquiry'), ('contacted', 'Contacted'), ('booked', 'Booked / Confirmed'), ('cancelled', 'Cancelled')], default='new', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to=settings.AUTH_USER_MODEL)),
                ('activities', models.ManyToManyField(blank=True, to='travel.optionalactivity')),
            ],
            options={
                'verbose_name_plural': 'Enquiries & bookings',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('recipient', models.CharField(max_length=120)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='travel.enquiry')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('tour_code', models.CharField(blank=True, help_text='Leave blank to auto-generate (e.g. FTD-0012).', max_length=20, null=True, unique=True)),
                ('tour_type', models.CharField(choices=[('individual', 'Individual / Customised'), ('group', 'Group (fixed departure)'), ('corporate', 'Corporate / MICE')], default='individual', max_length=12)),
                ('days', models.PositiveSmallIntegerField(default=5)),
                ('nights', models.PositiveSmallIntegerField(default=4)),
                ('short_description', models.CharField(max_length=240)),
                ('overview', models.TextField(blank=True)),
                ('base_price', models.PositiveIntegerField(help_text='Adult price per person, Standard hotels, before discount')),
                ('child_price', models.PositiveIntegerField(default=0, help_text='Child (2-11 yrs) price per person')),
                ('deluxe_upgrade', models.PositiveIntegerField(default=0, help_text='Extra per person for Deluxe hotels')),
                ('premium_upgrade', models.PositiveIntegerField(default=0, help_text='Extra per person for Premium hotels')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, help_text='0-90. Applied to base + hotel price')),
                ('offer_label', models.CharField(blank=True, help_text='e.g. Early-bird, Monsoon Sale', max_length=60)),
                ('offer_valid_till', models.DateField(blank=True, null=True)),
                ('is_event', models.BooleanField(default=False, verbose_name='Event / festival tour')),
                ('event_name', models.CharField(blank=True, help_text='e.g. Rann Utsav, Diwali in Jaipur', max_length=100)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('departure_dates', models.TextField(blank=True, help_text='Group tours: one departure date per line')),
                ('cover_image', models.ImageField(blank=True, upload_to='packages/')),
                ('cover_url', models.URLField(blank=True, help_text='Optional: link to an image instead of uploading')),
                ('youtube_url', models.URLField(blank=True, help_text='Any YouTube link (watch, youtu.be or shorts)')),
                ('inclusions', models.TextField(blank=True, help_text='One per line')),
                ('exclusions', models.TextField(blank=True, help_text='One per line')),
                ('tour_info', models.TextField(blank=True, help_text='Important notes, one per line (Title: text)')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide from the website')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('audiences', models.ManyToManyField(blank=True, related_name='packages', to='travel.audience')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='travel.destination')),
                ('themes', models.ManyToManyField(blank=True, related_name='packages', to='travel.theme')),
            ],
            options={
                'ordering': ['-is_featured', '-created'],
            },
        ),
        migrations.AddField(
            model_name='optionalactivity',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='travel.package'),
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('meals', models.CharField(blank=True, help_text='e.g. Breakfast, Dinner', max_length=80)),
                ('stay', models.CharField(blank=True, help_text='Overnight stay city / hotel', max_length=120)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='travel.package')),
            ],
            options={
                'verbose_name': 'Day-wise itinerary',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('premium', 'Premium')], default='standard', max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('star_rating', models.PositiveSmallIntegerField(default=3)),
                ('room_category', models.CharField(blank=True, help_text='e.g. Deluxe Sea-view Room', max_length=120)),
                ('nights', models.PositiveSmallIntegerField(default=1)),
                ('image', models.ImageField(blank=True, upload_to='hotels/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='travel.package')),
            ],
            options={
                'ordering': ['tier', 'id'],
            },
        ),
        migrations.AddField(
            model_name='enquiry',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='travel.package'),
        ),
        migrations.CreateModel(
            name='DepartureCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80)),
                ('surcharge', models.IntegerField(default=0, help_text='Extra per person from this city (0 = same as base)')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_cities', to='travel.package')),
            ],
            options={
                'verbose_name': 'Departure city & surcharge',
                'verbose_name_plural': 'Departure cities & surcharges',
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='travel.package')),
            ],
            options={
                'verbose_name': 'Gallery photo',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('home_city', models.CharField(blank=True, max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sightseeing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='sightseeing/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightseeing', to='travel.package')),
            ],
            options={
                'verbose_name': 'Sightseeing spot',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SavedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='travel.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('user', 'package')},
            },
        ),
    ]
