# Generated by Django 6.1.1 on 2026-09-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(default='Sai Samarth Holidays Pvt. Ltd.', max_length=80),
        ),
    ]
