# Generated by Django 6.1.1 on 2026-09-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_sitesettings_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='holidays@saisamarthholidays.in', help_text='Enquiries are also sent to this address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+91 9510088833', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(default='919510088833', help_text='Digits only with country code, e.g. 919876543210', max_length=20),
        ),
    ]
