# Generated by Django 5.2.17 on 2026-10-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_sitesettings_email_alter_sitesettings_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price_on_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='source_details',
            field=models.JSONField(blank=True, default=dict, help_text='Original imported tour details, preserved verbatim'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
