"""Curated Wikimedia Commons file pages for the demo destinations and landmarks."""

import hashlib
from urllib.parse import quote, unquote, urlparse

SOURCES = {
    "Goa|": "https://commons.wikimedia.org/wiki/File%3ABaga_Beach%2C_Calangute%2C_Goa.jpg",
    "Goa|Baga & Calangute Beach": "https://commons.wikimedia.org/wiki/File%3ABaga_Beach%2C_Calangute%2C_Goa.jpg",
    "Kerala Backwaters|": "https://commons.wikimedia.org/wiki/File%3AKerala_backwaters_houseboat.jpg",
    "Kerala Backwaters|Alleppey Houseboat Cruise": "https://commons.wikimedia.org/wiki/File%3AKerala_backwaters_houseboat.jpg",
    "Jaipur|": "https://commons.wikimedia.org/wiki/File%3AAmber_Fort-Jaipur-Rajasthan-.jpg",
    "Jaipur|Amber Fort": "https://commons.wikimedia.org/wiki/File%3AAmber_Fort-Jaipur-Rajasthan-.jpg",
    "Udaipur|": "https://commons.wikimedia.org/wiki/File%3ALake_Pichola_at_udaipur.jpg",
    "Udaipur|Lake Pichola Boat Ride": "https://commons.wikimedia.org/wiki/File%3ALake_Pichola_at_udaipur.jpg",
    "Jaisalmer|": "https://commons.wikimedia.org/wiki/File%3AJaisalmerFort.jpg",
    "Jaisalmer|Jaisalmer Fort": "https://commons.wikimedia.org/wiki/File%3AJaisalmerFort.jpg",
    "Jodhpur|": "https://commons.wikimedia.org/wiki/File%3AMehrangarh_Fort_at_Jodhpur%2C_Rajasthan%2C_India.jpg",
    "Jodhpur|Mehrangarh Fort": "https://commons.wikimedia.org/wiki/File%3AMehrangarh_Fort_at_Jodhpur%2C_Rajasthan%2C_India.jpg",
    "Pushkar|": "https://commons.wikimedia.org/wiki/File%3APushkar_Brahma_Temple.jpg",
    "Pushkar|Brahma Temple": "https://commons.wikimedia.org/wiki/File%3APushkar_Brahma_Temple.jpg",
    "Ranthambore|": "https://commons.wikimedia.org/wiki/File%3ATiger_Ranthambore_.jpg",
    "Ranthambore|Tiger Safari Zone 1-5": "https://commons.wikimedia.org/wiki/File%3ATiger_Ranthambore_.jpg",
    "Kashmir|": "https://commons.wikimedia.org/wiki/File%3AShikara_Dal_Lake.jpg",
    "Kashmir|Dal Lake Shikara": "https://commons.wikimedia.org/wiki/File%3AShikara_Dal_Lake.jpg",
    "Ladakh|": "https://commons.wikimedia.org/wiki/File%3APangong_lake%2C_Ladakh_image.jpg",
    "Ladakh|Pangong Lake": "https://commons.wikimedia.org/wiki/File%3APangong_lake%2C_Ladakh_image.jpg",
    "Manali|": "https://commons.wikimedia.org/wiki/File%3ASolang_Valley_Manali.JPG",
    "Manali|Solang Valley": "https://commons.wikimedia.org/wiki/File%3ASolang_Valley_Manali.JPG",
    "Shimla|": "https://commons.wikimedia.org/wiki/File%3AShimla_Mall_Road.jpg",
    "Shimla|Mall Road": "https://commons.wikimedia.org/wiki/File%3AShimla_Mall_Road.jpg",
    "Spiti Valley|": "https://commons.wikimedia.org/wiki/File%3AKey_Monastery%2C_Spiti_Valley%2C_Himachal_Pradesh.jpg",
    "Spiti Valley|Key Monastery": "https://commons.wikimedia.org/wiki/File%3AKey_Monastery%2C_Spiti_Valley%2C_Himachal_Pradesh.jpg",
    "Rishikesh|": "https://commons.wikimedia.org/wiki/File%3AGanga_Arti_At_Triveni_Ghat_In_Rishikesh.jpg",
    "Rishikesh|Ganga Aarti Triveni Ghat": "https://commons.wikimedia.org/wiki/File%3AGanga_Arti_At_Triveni_Ghat_In_Rishikesh.jpg",
    "Jim Corbett|": "https://commons.wikimedia.org/wiki/File%3ADhikala_grass_fields_at_Jim_Corbett_National_Park.jpg",
    "Jim Corbett|Jeep Safari Dhikala": "https://commons.wikimedia.org/wiki/File%3ADhikala_grass_fields_at_Jim_Corbett_National_Park.jpg",
    "Andaman Islands|": "https://commons.wikimedia.org/wiki/File%3ARadhanagar_Beach_on_Havelock_Island_of_Andaman_and_Nicobar_Archipelago..jpg",
    "Andaman Islands|Radhanagar Beach": "https://commons.wikimedia.org/wiki/File%3ARadhanagar_Beach_on_Havelock_Island_of_Andaman_and_Nicobar_Archipelago..jpg",
    "Darjeeling & Gangtok|": "https://commons.wikimedia.org/wiki/File%3ATiger_Hill_Darjeeling_West_Bengal_India_%282%29.JPG",
    "Darjeeling & Gangtok|Tiger Hill Sunrise": "https://commons.wikimedia.org/wiki/File%3ATiger_Hill_Darjeeling_West_Bengal_India_%282%29.JPG",
    "Meghalaya|": "https://commons.wikimedia.org/wiki/File%3ALiving-Root-Bridge.jpg",
    "Meghalaya|Living Root Bridge": "https://commons.wikimedia.org/wiki/File%3ALiving-Root-Bridge.jpg",
    "Kaziranga|": "https://commons.wikimedia.org/wiki/File%3AKaziranga_Elephant.jpg",
    "Kaziranga|Elephant Safari": "https://commons.wikimedia.org/wiki/File%3AKaziranga_Elephant.jpg",
    "Varanasi|": "https://commons.wikimedia.org/wiki/File%3APan_Shot%2C_Ganga_Aarti_at_Dashashwamedh_Ghat%2C_Varanasi.jpg",
    "Varanasi|Ganga Aarti Dashashwamedh": "https://commons.wikimedia.org/wiki/File%3APan_Shot%2C_Ganga_Aarti_at_Dashashwamedh_Ghat%2C_Varanasi.jpg",
    "Golden Triangle|": "https://commons.wikimedia.org/wiki/File%3ATaj_Mahal_....JPG",
    "Golden Triangle|Taj Mahal Sunrise": "https://commons.wikimedia.org/wiki/File%3ATaj_Mahal_....JPG",
    "Rann of Kutch|": "https://commons.wikimedia.org/wiki/File%3ASunset_at_Rann_of_Kutch%2C_Dhordo%2C_Gujarat.jpg",
    "Rann of Kutch|White Rann Sunset": "https://commons.wikimedia.org/wiki/File%3ASunset_at_Rann_of_Kutch%2C_Dhordo%2C_Gujarat.jpg",
    "Gir & Somnath|": "https://commons.wikimedia.org/wiki/File%3AIndian_Gir_Lion.jpg",
    "Gir & Somnath|Gir Lion Safari": "https://commons.wikimedia.org/wiki/File%3AIndian_Gir_Lion.jpg",
    "Mysore & Coorg|": "https://commons.wikimedia.org/wiki/File%3AMysore_Palace..JPG",
    "Mysore & Coorg|Mysore Palace": "https://commons.wikimedia.org/wiki/File%3AMysore_Palace..JPG",
    "Hampi|": "https://commons.wikimedia.org/wiki/File%3AHampi_virupaksha_temple.jpg",
    "Hampi|Virupaksha Temple": "https://commons.wikimedia.org/wiki/File%3AHampi_virupaksha_temple.jpg",
    "Ooty & Coonoor|": "https://commons.wikimedia.org/wiki/File%3ARailway_to_Coonor_%26_Ooty%2C_1900-01-02..jpg",
    "Ooty & Coonoor|Nilgiri Mountain Railway": "https://commons.wikimedia.org/wiki/File%3ARailway_to_Coonor_%26_Ooty%2C_1900-01-02..jpg",
    "Pondicherry|": "https://commons.wikimedia.org/wiki/File%3APuducherry-White_Town-WUS02349.jpg",
    "Pondicherry|White Town Walk": "https://commons.wikimedia.org/wiki/File%3APuducherry-White_Town-WUS02349.jpg",
    "Amritsar|": "https://commons.wikimedia.org/wiki/File%3AThe_Golden_Temple_in_Amrithsar_.jpg",
    "Amritsar|Golden Temple": "https://commons.wikimedia.org/wiki/File%3AThe_Golden_Temple_in_Amrithsar_.jpg",
    "Lakshadweep|": "https://commons.wikimedia.org/wiki/File%3AAgatti_Island_Lakshadweep.jpg",
    "Lakshadweep|Agatti Lagoon": "https://commons.wikimedia.org/wiki/File%3AAgatti_Island_Lakshadweep.jpg",
    "Dubai|": "https://commons.wikimedia.org/wiki/File%3ADubai_Burj_Khalifa.jpg",
    "Dubai|Burj Khalifa At The Top": "https://commons.wikimedia.org/wiki/File%3ADubai_Burj_Khalifa.jpg",
    "Bangkok & Pattaya|": "https://commons.wikimedia.org/wiki/File%3AGrand_Palace_Bangkok%2C_Thailand.jpg",
    "Bangkok & Pattaya|Grand Palace & Wat Pho": "https://commons.wikimedia.org/wiki/File%3AGrand_Palace_Bangkok%2C_Thailand.jpg",
    "Phuket & Krabi|": "https://commons.wikimedia.org/wiki/File%3APhi_Phi_Island_Tour_%284296487895%29.jpg",
    "Phuket & Krabi|Phi Phi Island Tour": "https://commons.wikimedia.org/wiki/File%3APhi_Phi_Island_Tour_%284296487895%29.jpg",
    "Bali|": "https://commons.wikimedia.org/wiki/File%3AUluwatu_Temple%2C_kecak_dance_%2848219683356%29.jpg",
    "Bali|Uluwatu Temple Kecak Dance": "https://commons.wikimedia.org/wiki/File%3AUluwatu_Temple%2C_kecak_dance_%2848219683356%29.jpg",
    "Singapore|": "https://commons.wikimedia.org/wiki/File%3AGardens_by_the_Bay_Singapore_%28aerial_view%29.jpg",
    "Singapore|Gardens by the Bay": "https://commons.wikimedia.org/wiki/File%3AGardens_by_the_Bay_Singapore_%28aerial_view%29.jpg",
    "Malaysia|": "https://commons.wikimedia.org/wiki/File%3APetronas_Twin_Towers_%2811.5.25%29.jpg",
    "Malaysia|Petronas Twin Towers": "https://commons.wikimedia.org/wiki/File%3APetronas_Twin_Towers_%2811.5.25%29.jpg",
    "Maldives|": "https://commons.wikimedia.org/wiki/File%3ASandbank_Malediven_%2829447070765%29.jpg",
    "Maldives|Sandbank Picnic": "https://commons.wikimedia.org/wiki/File%3ASandbank_Malediven_%2829447070765%29.jpg",
    "Sri Lanka|": "https://commons.wikimedia.org/wiki/File%3APhoto_of_Sigiriya_rock.jpg",
    "Sri Lanka|Sigiriya Rock": "https://commons.wikimedia.org/wiki/File%3APhoto_of_Sigiriya_rock.jpg",
    "Vietnam|": "https://commons.wikimedia.org/wiki/File%3AHALONG_BAY_.jpg",
    "Vietnam|Ha Long Bay Cruise": "https://commons.wikimedia.org/wiki/File%3AHALONG_BAY_.jpg",
    "Nepal|": "https://commons.wikimedia.org/wiki/File%3APashupatinath_Temple_%28%E0%A4%AA%E0%A4%B6%E0%A5%81%E0%A4%AA%E0%A4%A4%E0%A4%BF%E0%A4%A8%E0%A4%BE%E0%A4%A5_%E0%A4%AE%E0%A4%A8%E0%A5%8D%E0%A4%A6%E0%A4%BF%E0%A4%B0%29_01.jpg",
    "Nepal|Pashupatinath Temple": "https://commons.wikimedia.org/wiki/File%3APashupatinath_Temple_%28%E0%A4%AA%E0%A4%B6%E0%A5%81%E0%A4%AA%E0%A4%A4%E0%A4%BF%E0%A4%A8%E0%A4%BE%E0%A4%A5_%E0%A4%AE%E0%A4%A8%E0%A5%8D%E0%A4%A6%E0%A4%BF%E0%A4%B0%29_01.jpg",
    "Bhutan|": "https://commons.wikimedia.org/wiki/File%3AThe_Tiger%27s_Nest_Monastery_Bhutan.jpg",
    "Bhutan|Tiger's Nest Monastery": "https://commons.wikimedia.org/wiki/File%3AThe_Tiger%27s_Nest_Monastery_Bhutan.jpg",
    "Japan|": "https://commons.wikimedia.org/wiki/File%3AFushimi_Inari_shrine_%2C_%E4%BC%8F%E8%A6%8B%E7%A8%B2%E8%8D%B7%E5%A4%A7%E7%A4%BE_-_panoramio_%2810%29.jpg",
    "Japan|Fushimi Inari Shrine": "https://commons.wikimedia.org/wiki/File%3AFushimi_Inari_shrine_%2C_%E4%BC%8F%E8%A6%8B%E7%A8%B2%E8%8D%B7%E5%A4%A7%E7%A4%BE_-_panoramio_%2810%29.jpg",
    "South Korea|": "https://commons.wikimedia.org/wiki/File%3AGyeongbokgung_Palace_%2855219197825%29.jpg",
    "South Korea|Gyeongbokgung Palace": "https://commons.wikimedia.org/wiki/File%3AGyeongbokgung_Palace_%2855219197825%29.jpg",
    "Turkey|": "https://commons.wikimedia.org/wiki/File%3AHot-air_ballooning_in_Cappadocia_%2852397863260%29.jpg",
    "Turkey|Hot Air Balloon Cappadocia": "https://commons.wikimedia.org/wiki/File%3AHot-air_ballooning_in_Cappadocia_%2852397863260%29.jpg",
    "Egypt|": "https://commons.wikimedia.org/wiki/File%3APyramids_of_Giza%2C_Egypt.jpg",
    "Egypt|Pyramids of Giza": "https://commons.wikimedia.org/wiki/File%3APyramids_of_Giza%2C_Egypt.jpg",
    "Switzerland|": "https://commons.wikimedia.org/wiki/File%3ATop_of_Europe.jpg",
    "Switzerland|Jungfraujoch Top of Europe": "https://commons.wikimedia.org/wiki/File%3ATop_of_Europe.jpg",
    "Paris & Amsterdam|": "https://commons.wikimedia.org/wiki/File%3AEiffel_Tower..jpg",
    "Paris & Amsterdam|Eiffel Tower": "https://commons.wikimedia.org/wiki/File%3AEiffel_Tower..jpg",
    "Greece|": "https://commons.wikimedia.org/wiki/File%3ASunset_in_Oia%2C_Santorini.jpg",
    "Greece|Oia Sunset Santorini": "https://commons.wikimedia.org/wiki/File%3ASunset_in_Oia%2C_Santorini.jpg",
    "Mauritius|": "https://commons.wikimedia.org/wiki/File%3AIle_aux_cerfs_%28%28Mauritius_Islands%29.JPG",
    "Mauritius|Ile Aux Cerfs": "https://commons.wikimedia.org/wiki/File%3AIle_aux_cerfs_%28%28Mauritius_Islands%29.JPG",
    "Seychelles|": "https://commons.wikimedia.org/wiki/File%3AAnse_Lazio_Beach_Seychelles_%2824748949707%29.jpg",
    "Seychelles|Anse Lazio Beach": "https://commons.wikimedia.org/wiki/File%3AAnse_Lazio_Beach_Seychelles_%2824748949707%29.jpg",
    "Australia|": "https://commons.wikimedia.org/wiki/File%3AThe_Sydney_Opera_House._Australia.jpg",
    "Australia|Sydney Opera House": "https://commons.wikimedia.org/wiki/File%3AThe_Sydney_Opera_House._Australia.jpg",
    "New Zealand|": "https://commons.wikimedia.org/wiki/File%3AMilford_Sound_%28New_Zealand%29.JPG",
    "New Zealand|Milford Sound": "https://commons.wikimedia.org/wiki/File%3AMilford_Sound_%28New_Zealand%29.JPG",
    "Hong Kong & Macau|": "https://commons.wikimedia.org/wiki/File%3AHongKong_VictoriaPeak.jpg",
    "Hong Kong & Macau|Victoria Peak": "https://commons.wikimedia.org/wiki/File%3AHongKong_VictoriaPeak.jpg",
    "Kenya Safari|": "https://commons.wikimedia.org/wiki/File%3AKenya_safari.jpg",
    "Kenya Safari|Masai Mara Game Drive": "https://commons.wikimedia.org/wiki/File%3AKenya_safari.jpg",
    "Azerbaijan (Baku)|": "https://commons.wikimedia.org/wiki/File%3AFlame_Towers.jpg",
    "Azerbaijan (Baku)|Flame Towers": "https://commons.wikimedia.org/wiki/File%3AFlame_Towers.jpg",
    "USA - East Coast|": "https://commons.wikimedia.org/wiki/File%3AStatue_of_Liberty_United_States_of_America_-_USA_%289897946896%29.jpg",
    "USA - East Coast|Statue of Liberty": "https://commons.wikimedia.org/wiki/File%3AStatue_of_Liberty_United_States_of_America_-_USA_%289897946896%29.jpg",
    "Goa|Old Goa Churches": "https://commons.wikimedia.org/wiki/File%3AOld_Goa_Churches.jpg",
    "Goa|Fort Aguada": "https://commons.wikimedia.org/wiki/File%3AFort_Aguada%2C_Goa%21.jpg",
    "Goa|Dudhsagar Falls": "https://commons.wikimedia.org/wiki/File%3ADudhsagar_Falls%2C_Goa.jpg",
    "Goa|Anjuna Flea Market": "https://commons.wikimedia.org/wiki/File%3AAnjuna_flea-market_%2871905385%29.jpg",
    "Kerala Backwaters|Munnar Tea Gardens": "https://commons.wikimedia.org/wiki/File%3ATea_Gardens_in_Munnar.jpg",
    "Kerala Backwaters|Periyar Wildlife Sanctuary": "https://commons.wikimedia.org/wiki/File%3APeriyar_Wildlife_sanctuary.jpg",
    "Kerala Backwaters|Kovalam Beach": "https://commons.wikimedia.org/wiki/File%3AKovalam_Beach_in_Kerala.jpg",
    "Kerala Backwaters|Kathakali Show": "https://commons.wikimedia.org/wiki/File%3AKathakali_%28Kerala%29.jpg",
    "Jaipur|City Palace": "https://commons.wikimedia.org/wiki/File%3AJaipur_City_Palace%2C_Rajasthan.jpg",
    "Jaipur|Hawa Mahal": "https://commons.wikimedia.org/wiki/File%3AHawa_mahal%2C_JAIPUR..jpg",
    "Jaipur|Jantar Mantar": "https://commons.wikimedia.org/wiki/File%3AFull_view_of_jantar_mantar_%2CJaipur.jpg",
    "Jaipur|Chokhi Dhani Village": "https://commons.wikimedia.org/wiki/File%3AChokhi_dhani.jpg",
    "Udaipur|City Palace Udaipur": "https://commons.wikimedia.org/wiki/File%3ACity_palace_%28Udaipur%29.jpg",
    "Udaipur|Saheliyon Ki Bari": "https://commons.wikimedia.org/wiki/File%3ASaheliyon-ki-Bari_%28in_Udaipur%29.jpg",
    "Udaipur|Sajjangarh Monsoon Palace": "https://commons.wikimedia.org/wiki/File%3AMonsoon_palace_udaipur.jpg",
    "Udaipur|Bagore Ki Haveli": "https://commons.wikimedia.org/wiki/File%3AInteriors_of_Bagore_Ki_Haveli.jpg",
    "Jaisalmer|Sam Sand Dunes": "https://commons.wikimedia.org/wiki/File%3ASam_dunes_%28Jaisalmer%29.jpg",
    "Jaisalmer|Patwon Ki Haveli": "https://commons.wikimedia.org/wiki/File%3APatwon_ki_haveli_-_Jaisalmer.jpg",
    "Jaisalmer|Gadisar Lake": "https://commons.wikimedia.org/wiki/File%3AGadisar_Lake_in_Jaisalmer.jpg",
    "Jaisalmer|Desert Camp Cultural Night": "https://commons.wikimedia.org/wiki/File%3ADesert_Night_Camp_%2817232035296%29.jpg",
    "Jodhpur|Umaid Bhawan Palace": "https://commons.wikimedia.org/wiki/File%3AUmaid_Bhawan_Palace_%2839889344651%29.jpg",
    "Jodhpur|Jaswant Thada": "https://commons.wikimedia.org/wiki/File%3AJaswant_Thada%2C_Jodhpur%2C.jpg",
    "Jodhpur|Clock Tower Market": "https://commons.wikimedia.org/wiki/File%3AClock_tower_Sardar_market_jodhpur.jpg",
    "Jodhpur|Bishnoi Village Safari": "https://commons.wikimedia.org/wiki/File%3ABishnoi_village.jpg",
    "Pushkar|Pushkar Lake Ghats": "https://commons.wikimedia.org/wiki/File%3APushkar_Lake_Ghats_Rajasthan_India.jpg",
    "Pushkar|Savitri Temple Ropeway": "https://commons.wikimedia.org/wiki/File%3APushkar_Ropeway.jpg",
    "Pushkar|Camel Safari": "https://commons.wikimedia.org/wiki/File%3ACamel_Safari_%C3%A0_Pushkar_%28Rajasthan%29_%285%29.jpg",
    "Pushkar|Pushkar Bazaar": "https://commons.wikimedia.org/wiki/File%3APushkar.jpg",
    "Ranthambore|Ranthambore Fort": "https://commons.wikimedia.org/wiki/File%3ARanthambore_Fort_with_local_Ladies..JPG",
    "Ranthambore|Padam Talao": "https://commons.wikimedia.org/wiki/File%3APadam_Talao.jpg",
    "Kashmir|Mughal Gardens": "https://commons.wikimedia.org/wiki/File%3AMughal_garden_pro.jpg",
    "Kashmir|Gulmarg Gondola": "https://commons.wikimedia.org/wiki/File%3AGulmarg_Gondola%2C_Kashmir.jpg",
    "Kashmir|Pahalgam Valley": "https://commons.wikimedia.org/wiki/File%3APahalgam_Valley.jpg",
    "Kashmir|Sonmarg Glacier": "https://commons.wikimedia.org/wiki/File%3AGlacier_en_Route_from_Sonmarg_to_Srinagar_-_Jammu_%26_Kashmir_-_India_%2826238728893%29.jpg",
    "Ladakh|Nubra Valley": "https://commons.wikimedia.org/wiki/File%3ALadakh-Valley.jpg",
    "Ladakh|Khardung La": "https://commons.wikimedia.org/wiki/File%3AKhardung_La.jpg",
    "Ladakh|Thiksey Monastery": "https://commons.wikimedia.org/wiki/File%3AThikse_Monastery_.jpg",
    "Ladakh|Magnetic Hill": "https://commons.wikimedia.org/wiki/File%3ALadakh_-_Magnetic_Hill.jpg",
    "Manali|Rohtang / Atal Tunnel": "https://commons.wikimedia.org/wiki/File%3ARohtang_Atal_Tunnel.jpg",
    "Manali|Hadimba Temple": "https://commons.wikimedia.org/wiki/File%3AHadimba_Temple.jpg",
    "Manali|Old Manali Cafes": "https://commons.wikimedia.org/wiki/File%3AOld_Manali.jpg",
    "Manali|Beas River Rafting": "https://commons.wikimedia.org/wiki/File%3ABeas_river_in_manali.jpg",
    "Shimla|Kufri": "https://commons.wikimedia.org/wiki/File%3AKufri_in_Shimla_3.jpg",
    "Shimla|Jakhu Temple": "https://commons.wikimedia.org/wiki/File%3AJakhu_temple_Shimla.jpg",
    "Shimla|Christ Church": "https://commons.wikimedia.org/wiki/File%3AChrist_Church_%28Shimla%29.jpg",
    "Shimla|Toy Train Ride": "https://commons.wikimedia.org/wiki/File%3AShimla_Kalka_Toy_Train.jpg",
    "Spiti Valley|Chandratal Lake": "https://commons.wikimedia.org/wiki/File%3AChandratal_lake_of_Spiti_valley.jpg",
    "Spiti Valley|Kaza Village": "https://commons.wikimedia.org/wiki/File%3AKaza.jpg",
    "Spiti Valley|Pin Valley": "https://commons.wikimedia.org/wiki/File%3ASpiti_Valley.jpg",
    "Spiti Valley|Langza Fossil Village": "https://commons.wikimedia.org/wiki/File%3AView_towards_Spiti_Valley_from_Langza%2C_Himachal_Pradesh%2C_India.jpg",
    "Rishikesh|Laxman Jhula": "https://commons.wikimedia.org/wiki/File%3ALaxman_Jhula%2C_Rishikesh.jpg",
    "Rishikesh|White Water Rafting": "https://commons.wikimedia.org/wiki/File%3ARafting_in_rishikesh.jpg",
    "Rishikesh|Beatles Ashram": "https://commons.wikimedia.org/wiki/File%3ABeatles_Ashram_At_Rishikesh.jpg",
    "Rishikesh|Neelkanth Mahadev": "https://commons.wikimedia.org/wiki/File%3ANeelKanth_Mahadev_Temple.JPG",
    "Jim Corbett|Corbett Falls": "https://commons.wikimedia.org/wiki/File%3ACorbett_falls.jpg",
    "Jim Corbett|Garjia Devi Temple": "https://commons.wikimedia.org/wiki/File%3AGarjia_Temple_in_Jim_Corbett_National_Park_Uttrakhand_-_Corbett_The_Baagh.jpg",
    "Jim Corbett|Kosi River Walk": "https://commons.wikimedia.org/wiki/File%3AKosi_River_by_the_Sides_of_Jim_Corbett.jpg",
    "Jim Corbett|Jungle Canter Safari": "https://commons.wikimedia.org/wiki/File%3AJim_Corbett_national_park_jungle.jpg",
    "Andaman Islands|Cellular Jail Light & Sound": "https://commons.wikimedia.org/wiki/File%3ACells_during_light_and_sound_show_-_Cellular_Jail.jpg",
    "Andaman Islands|Elephant Beach Snorkelling": "https://commons.wikimedia.org/wiki/File%3ASnorkeling_at_Elephant_Beach_on_Havelock_island_of_Andaman_and_Nicobar_Archipelago.JPG",
    "Andaman Islands|Ross Island": "https://commons.wikimedia.org/wiki/File%3ARoss_Island_Andaman_Islands.jpg",
    "Andaman Islands|Neil Island": "https://commons.wikimedia.org/wiki/File%3ANeil_Island_Andaman_Islands.jpg",
    "Darjeeling & Gangtok|Toy Train Joyride": "https://commons.wikimedia.org/wiki/File%3ADarjeeling_Toy_Train_%2841474527115%29.jpg",
    "Darjeeling & Gangtok|Tsomgo Lake": "https://commons.wikimedia.org/wiki/File%3ATsomgo_lake.jpg",
    "Darjeeling & Gangtok|Nathula Pass": "https://commons.wikimedia.org/wiki/File%3ANathula_Pass.jpg",
    "Darjeeling & Gangtok|Rumtek Monastery": "https://commons.wikimedia.org/wiki/File%3ARumtek_monastery.jpg",
    "Meghalaya|Dawki River": "https://commons.wikimedia.org/wiki/File%3ADawki_River%2C_Dawki%2C_Meghalaya.jpg",
    "Meghalaya|Mawlynnong Village": "https://commons.wikimedia.org/wiki/File%3AMawlynnong_Village%2C_Meghalaya_%282%29.jpg",
    "Meghalaya|Nohkalikai Falls": "https://commons.wikimedia.org/wiki/File%3ANohkalikai_Falls_in_Meghalaya%2C_India.jpg",
    "Meghalaya|Elephant Falls": "https://commons.wikimedia.org/wiki/File%3AElephant_Falls_from_Meghalaya.jpg",
    "Kaziranga|Jeep Safari Central Range": "https://commons.wikimedia.org/wiki/File%3AJeep_Safari_Kaziranga%2C_Central_Zone_%28Kohara%29.jpg",
    "Kaziranga|Tea Estate Visit": "https://commons.wikimedia.org/wiki/File%3ATea_gardens_of_Kaziranga_National_Park%2C_Assam.jpg",
    "Kaziranga|Orchid Park": "https://commons.wikimedia.org/wiki/File%3AKaziranga_National_Orchid_and_Biodiversity_Park.jpg",
    "Varanasi|Kashi Vishwanath": "https://commons.wikimedia.org/wiki/File%3AKashi_vishwanath_temple_varanasi.jpg",
    "Varanasi|Sarnath": "https://commons.wikimedia.org/wiki/File%3ASARNATH.jpg",
    "Varanasi|Sunrise Boat Ride": "https://commons.wikimedia.org/wiki/File%3ASunrise_boat_ride%2C_Varanasi.jpg",
    "Varanasi|Ramnagar Fort": "https://commons.wikimedia.org/wiki/File%3ATaking_a_Photo_outside_Ramnagar_Fort_-_Varanasi_-_Uttar_Pradesh_-_India_%2812519347063%29.jpg",
    "Golden Triangle|Red Fort": "https://commons.wikimedia.org/wiki/File%3ARed_Fort..JPG",
    "Golden Triangle|Qutub Minar": "https://commons.wikimedia.org/wiki/File%3AThe_Golden_Qutub_Minar.jpg",
    "Golden Triangle|Agra Fort": "https://commons.wikimedia.org/wiki/File%3AAgra_fort_.jpg",
    "Golden Triangle|Fatehpur Sikri": "https://commons.wikimedia.org/wiki/File%3AFatehpur_Sikri_%28c%29.jpg",
    "Rann of Kutch|Kalo Dungar": "https://commons.wikimedia.org/wiki/File%3ARann_of_Kutch_from_Kala_Dungar.jpg",
    "Rann of Kutch|Bhujodi Craft Village": "https://commons.wikimedia.org/wiki/File%3AThe_Vice_President%2C_Shri_Mohd._Hamid_Ansari_visiting_the_Handicraft_exhibition_and_manufacturing_unit_in_Shrujan%2C_at_Village_Bhujodi%2C_in_Kachchh%2C_Gujarat_on_February_04%2C_2015.jpg",
    "Rann of Kutch|Mandvi Beach": "https://commons.wikimedia.org/wiki/File%3AMandvi_beach_kutch.jpg",
    "Gir & Somnath|Somnath Temple": "https://commons.wikimedia.org/wiki/File%3ASomnath_temple_Gujarat_India.jpg",
    "Gir & Somnath|Diu Beach": "https://commons.wikimedia.org/wiki/File%3ASomnath_beach.jpg",
    "Gir & Somnath|Junagadh Fort": "https://commons.wikimedia.org/wiki/File%3AJunagadh_Fort.jpg",
    "Gir & Somnath|Devalia Safari Park": "https://commons.wikimedia.org/wiki/File%3AMajestic_Asiatic_Lions_in_Devalia_Safari_Park_in_Gir_National_Forest%2C_Gujarat%2C_India.jpg",
    "Mysore & Coorg|Chamundi Hills": "https://commons.wikimedia.org/wiki/File%3A%2A%22Chamundesvari_Temple%2C_Chamundi_Hill%2C_Mysore%2C%22_a_photo_from_the_1890%27s%2A_%28BL%29.jpg",
    "Mysore & Coorg|Abbey Falls": "https://commons.wikimedia.org/wiki/File%3AAbbeyFallsCoorg.jpg",
    "Mysore & Coorg|Dubare Elephant Camp": "https://commons.wikimedia.org/wiki/File%3ADubare_Elephant_Camp.jpg",
    "Mysore & Coorg|Coffee Plantation Walk": "https://commons.wikimedia.org/wiki/File%3ACoffee_Plantation_in_Coorg..jpg",
    "Hampi|Vittala Temple Stone Chariot": "https://commons.wikimedia.org/wiki/File%3AStone_Chariot_of_Vitthala_Temple_Hampi.jpg",
    "Hampi|Matanga Hill Sunrise": "https://commons.wikimedia.org/wiki/File%3AHampi_landscape_from_Matanga_Hill%2C_Hampi%2C_India.jpg",
    "Hampi|Coracle Ride": "https://commons.wikimedia.org/wiki/File%3ACoracle_Ride.jpg",
    "Hampi|Lotus Mahal": "https://commons.wikimedia.org/wiki/File%3ALOTUS_MAHAL%2C_HAMPI.jpg",
    "Ooty & Coonoor|Botanical Gardens": "https://commons.wikimedia.org/wiki/File%3ABotanical_Garden_%28Ooty%29.jpg",
    "Ooty & Coonoor|Doddabetta Peak": "https://commons.wikimedia.org/wiki/File%3ADoddabetta_peak.jpg",
    "Ooty & Coonoor|Sim's Park": "https://commons.wikimedia.org/wiki/File%3ASim%27s_Park%2C_Coonoor_JEG9192.jpg",
    "Ooty & Coonoor|Tea Factory": "https://commons.wikimedia.org/wiki/File%3AOoty-tea-factory.jpg",
    "Pondicherry|Auroville": "https://commons.wikimedia.org/wiki/File%3AAuroville_Pondicherry_.JPG",
    "Pondicherry|Paradise Beach": "https://commons.wikimedia.org/wiki/File%3AParadise_beach_in_pondicherry.jpg",
    "Pondicherry|Promenade Beach": "https://commons.wikimedia.org/wiki/File%3ABeach_Promenade_in_Pondicherry.jpg",
    "Pondicherry|Sri Aurobindo Ashram": "https://commons.wikimedia.org/wiki/File%3ASri_Aurobindo_Ashram%2C_a_spiritual_ashram_of_Sri_Aurobindo_in_Pondicherry_08.jpg",
    "Amritsar|Wagah Border Ceremony": "https://commons.wikimedia.org/wiki/File%3AWagha_Border%2C_Ceremony.jpg",
    "Amritsar|Jallianwala Bagh": "https://commons.wikimedia.org/wiki/File%3AThe_Jallianwala_Bagh_memorial_in_Amrithsar_.jpg",
    "Amritsar|Partition Museum": "https://commons.wikimedia.org/wiki/File%3APartition_Museum%2C_Amritsar%2C_India.jpg",
    "Amritsar|Amritsari Food Trail": "https://commons.wikimedia.org/wiki/File%3AAmritsari_Aloo_Naan_Thali.jpg",
    "Lakshadweep|Bangaram Island": "https://commons.wikimedia.org/wiki/File%3ASea_off_Bangaram_island%2C_Lakshadweep.jpg",
    "Lakshadweep|Scuba Diving": "https://commons.wikimedia.org/wiki/File%3AScuba_diving_%40_Lakshadweep.jpg",
    "Lakshadweep|Kadmat Beach": "https://commons.wikimedia.org/wiki/File%3AA_beach_side_resort_at_Kadmat_Island%2C_Lakshadweep.jpg",
    "Dubai|Desert Safari with BBQ Dinner": "https://commons.wikimedia.org/wiki/File%3ADubai_desert.jpg",
    "Dubai|Dubai Marina Dhow Cruise": "https://commons.wikimedia.org/wiki/File%3ADUBAI_MARINA.jpg",
    "Dubai|Abu Dhabi Sheikh Zayed Mosque": "https://commons.wikimedia.org/wiki/File%3ASheikh_Zayed_Grand_Mosque%2C_the_entrance_to_the_parking_area..JPG",
    "Dubai|Palm Jumeirah & Atlantis": "https://commons.wikimedia.org/wiki/File%3ADubai_-_Palm_Jumeirah_%282%29.jpg",
    "Bangkok & Pattaya|Coral Island": "https://commons.wikimedia.org/wiki/File%3ACoral_island_of_Andaman.jpg",
    "Bangkok & Pattaya|Floating Market": "https://commons.wikimedia.org/wiki/File%3APattaya_Floating_Market_%281%29.jpg",
    "Bangkok & Pattaya|Alcazar Show": "https://commons.wikimedia.org/wiki/File%3AAlkazar_show1.jpg",
    "Bangkok & Pattaya|Sanctuary of Truth": "https://commons.wikimedia.org/wiki/File%3ASanctuary_of_Truth_Photgraph.jpg",
    "Phuket & Krabi|James Bond Island": "https://commons.wikimedia.org/wiki/File%3AJames_Bond_island.jpg",
    "Phuket & Krabi|Big Buddha": "https://commons.wikimedia.org/wiki/File%3AThe_Big_Buddha%2C_Phuket.jpg",
    "Phuket & Krabi|Phuket Old Town": "https://commons.wikimedia.org/wiki/File%3APhuket_Old_Town_1.jpg",
    "Phuket & Krabi|Four Islands Krabi": "https://commons.wikimedia.org/wiki/File%3AThailand_Route_4_Krabi_Province_1.jpg",
    "Bali|Ubud Rice Terraces": "https://commons.wikimedia.org/wiki/File%3ARice_terraces%2C_Ubud%2C_Bali.jpg",
    "Bali|Nusa Penida": "https://commons.wikimedia.org/wiki/File%3ANusa_Penida_-_Bali.jpg",
    "Bali|Tanah Lot Sunset": "https://commons.wikimedia.org/wiki/File%3ASunset_in_Tanah_Lot%2C_Bali.jpg",
    "Bali|Mount Batur Sunrise Trek": "https://commons.wikimedia.org/wiki/File%3AMount_Batur_Bali.jpg",
    "Singapore|Universal Studios": "https://commons.wikimedia.org/wiki/File%3AUniversal_Studios_Singapore.jpg",
    "Singapore|Marina Bay Sands": "https://commons.wikimedia.org/wiki/File%3AMarina_Bay_Sands%2C_Singapore_%28Image_1%29.jpg",
    "Singapore|Night Safari": "https://commons.wikimedia.org/wiki/File%3ASingapore_and_Malaysia_at_Night_%28154170%29.jpg",
    "Singapore|Sentosa Island": "https://commons.wikimedia.org/wiki/File%3ASentosa_Island.jpg",
    "Malaysia|Genting Highlands": "https://commons.wikimedia.org/wiki/File%3AGenting_Highlands_%281%29.JPG",
    "Malaysia|Batu Caves": "https://commons.wikimedia.org/wiki/File%3ABatu_caves_photos_malaysia_%288%29.jpg",
    "Malaysia|Langkawi Sky Bridge": "https://commons.wikimedia.org/wiki/File%3ALangkawi_Sky_Bridge%2C_Malaysia.jpg",
    "Malaysia|Putrajaya": "https://commons.wikimedia.org/wiki/File%3APutrajaya%2C_Malaysia.jpg",
    "Maldives|Snorkelling with Turtles": "https://commons.wikimedia.org/wiki/File%3ASnorkeling_in_the_Indian_Ocean_in_the_Maldives..JPG",
    "Maldives|Sunset Dolphin Cruise": "https://commons.wikimedia.org/wiki/File%3AMaldives_sunset.jpg",
    "Maldives|Overwater Spa": "https://commons.wikimedia.org/wiki/File%3AAnantara_Kihavah_-_Aerial_Hero_Shot_2024.jpg",
    "Maldives|Local Island Visit": "https://commons.wikimedia.org/wiki/File%3AMaldives_island.JPG",
    "Sri Lanka|Kandy Temple of the Tooth": "https://commons.wikimedia.org/wiki/File%3ATemple_of_tooth_kandy%2C_main_shrine_jpg.jpg",
    "Sri Lanka|Nuwara Eliya Tea Country": "https://commons.wikimedia.org/wiki/File%3ATea_country.jpg",
    "Sri Lanka|Galle Fort": "https://commons.wikimedia.org/wiki/File%3AGALLE_FORT.jpg",
    "Sri Lanka|Yala Safari": "https://commons.wikimedia.org/wiki/File%3AYala_Nationalpark_Sri_Lanka_%2830073496455%29.jpg",
    "Vietnam|Hoi An Lantern Town": "https://commons.wikimedia.org/wiki/File%3ALanterns_in_Hoi_An%2C_Vietnam_%2825708206924%29.jpg",
    "Vietnam|Cu Chi Tunnels": "https://commons.wikimedia.org/wiki/File%3AVietnamCuChiTunnels.jpg",
    "Vietnam|Ba Na Hills Golden Bridge": "https://commons.wikimedia.org/wiki/File%3AGolden_Bridge%2C_Ba_Na_Hills%2C_Vietnam_%2849056923018%29.jpg",
    "Vietnam|Hanoi Old Quarter": "https://commons.wikimedia.org/wiki/File%3AVietnam_hanoi_old_quarter.jpg",
    "Nepal|Phewa Lake": "https://commons.wikimedia.org/wiki/File%3APhewa.lake.jpg",
    "Nepal|Sarangkot Sunrise": "https://commons.wikimedia.org/wiki/File%3ASarangkot%2C_Nepal-WLV-1718.jpg",
    "Nepal|Boudhanath Stupa": "https://commons.wikimedia.org/wiki/File%3ABoudhanath_Stupa_.jpg",
    "Nepal|Paragliding Pokhara": "https://commons.wikimedia.org/wiki/File%3APokhara_Paragliding.jpg",
    "Bhutan|Punakha Dzong": "https://commons.wikimedia.org/wiki/File%3APunakhaDzong.jpg",
    "Bhutan|Dochula Pass": "https://commons.wikimedia.org/wiki/File%3ABhutan_drochula_pass.jpg",
    "Bhutan|Thimphu Buddha Point": "https://commons.wikimedia.org/wiki/File%3AThimphu_from_Buddha_point.jpg",
    "Bhutan|Paro Valley": "https://commons.wikimedia.org/wiki/File%3AThe_view_of_Paro_Valley_%2837783820352%29.jpg",
    "Japan|Shibuya Crossing": "https://commons.wikimedia.org/wiki/File%3AShibuya_Crossing_in_July_2026.jpg",
    "Japan|Mount Fuji & Hakone": "https://commons.wikimedia.org/wiki/File%3AMt._Fuji_from_Hakone.jpg",
    "Japan|Arashiyama Bamboo Grove": "https://commons.wikimedia.org/wiki/File%3AArashiyama_Bamboo_Grove.jpg",
    "Japan|Bullet Train Experience": "https://commons.wikimedia.org/wiki/File%3AJapanese_bullet_train_at_NRM.JPG",
    "South Korea|Nami Island": "https://commons.wikimedia.org/wiki/File%3A%EB%82%A8%EC%9D%B4%EC%84%AC_%2848%29.JPG",
    "South Korea|Myeongdong Street Food": "https://commons.wikimedia.org/wiki/File%3AStreet_food_in_Myeondong%2C_South_Korea.jpg",
    "South Korea|Jeju Island": "https://commons.wikimedia.org/wiki/File%3AJeju_Island%2C_South_Korea_%F0%9F%87%B0%F0%9F%87%B7.jpg",
    "South Korea|Han River Picnic": "https://commons.wikimedia.org/wiki/File%3AHan_River%2C_Seoul%2C_Korea_%2810079688743%29.jpg",
    "Turkey|Hagia Sophia": "https://commons.wikimedia.org/wiki/File%3ATurkey-3019_-_Hagia_Sophia_%282216460729%29_%282%29.jpg",
    "Turkey|Bosphorus Cruise": "https://commons.wikimedia.org/wiki/File%3ABosphoruscruise.jpg",
    "Turkey|Pamukkale Terraces": "https://commons.wikimedia.org/wiki/File%3APamukkale_travertenleri.jpg",
    "Turkey|Grand Bazaar": "https://commons.wikimedia.org/wiki/File%3AGrand_bazaar.jpg",
    "Egypt|Nile Felucca": "https://commons.wikimedia.org/wiki/File%3AFelucca_on_the_Nile_in_Cairo.jpg",
    "Egypt|Valley of the Kings": "https://commons.wikimedia.org/wiki/File%3AValley_of_the_Kings_%28Luxor%2C_Egypt%29.jpg",
    "Egypt|Egyptian Museum": "https://commons.wikimedia.org/wiki/File%3AEgyptian_museum_at_Tahrir_Square%2C_Cairo..jpg",
    "Egypt|Luxor Karnak Temple": "https://commons.wikimedia.org/wiki/File%3AKarnak_Temple_%2C_Luxor_%2C_Egypt.jpg",
    "Switzerland|Lucerne Chapel Bridge": "https://commons.wikimedia.org/wiki/File%3AThe_Chapel_Bridge_in_Lucerne.jpg",
    "Switzerland|Mount Titlis": "https://commons.wikimedia.org/wiki/File%3AView_from_Mount_Titlis.jpg",
    "Switzerland|Interlaken": "https://commons.wikimedia.org/wiki/File%3AInterlaken%2C_the_Jungfrau%2C_from_the_Rugen%2C_Bernese_Oberland%2C_Switzerland-LCCN2001701179.jpg",
    "Switzerland|Glacier Express Ride": "https://commons.wikimedia.org/wiki/File%3AGlacier_express.jpg",
    "Paris & Amsterdam|Louvre Museum": "https://commons.wikimedia.org/wiki/File%3AThe_Louvre_Museum.jpg",
    "Paris & Amsterdam|Keukenhof Gardens": "https://commons.wikimedia.org/wiki/File%3AKeukenhof_Garden_%281%29.JPG",
    "Paris & Amsterdam|Canal Cruise Amsterdam": "https://commons.wikimedia.org/wiki/File%3AAmsterdam_Canal..JPG",
    "Paris & Amsterdam|Versailles Palace": "https://commons.wikimedia.org/wiki/File%3AThe_Palace_of_Versailles_%2824219937621%29.jpg",
    "Greece|Acropolis Athens": "https://commons.wikimedia.org/wiki/File%3AAcropolis_Athens_Greece.jpg",
    "Greece|Mykonos Windmills": "https://commons.wikimedia.org/wiki/File%3AMykonosWindmills.jpg",
    "Greece|Caldera Boat Tour": "https://commons.wikimedia.org/wiki/File%3ATour_boat_-_Santorini_near_Oia_-_Greece.jpg",
    "Greece|Delphi": "https://commons.wikimedia.org/wiki/File%3ADelphi%2C_Greece.jpg",
    "Mauritius|Seven Coloured Earths": "https://commons.wikimedia.org/wiki/File%3ASeven_coloured_earths_mauritius.jpg",
    "Mauritius|Catamaran Cruise": "https://commons.wikimedia.org/wiki/File%3ACatamaran_%286139225439%29.jpg",
    "Mauritius|Chamarel Waterfall": "https://commons.wikimedia.org/wiki/File%3AChamarel_Waterfall%2C_Mauritius.jpg",
    "Mauritius|Port Louis Market": "https://commons.wikimedia.org/wiki/File%3AMauritius_-_Port_Louis_%28Central_Market%29_%2817118303459%29.jpg",
    "Seychelles|Vallee de Mai": "https://commons.wikimedia.org/wiki/File%3AVallee_de_mai.jpg",
    "Seychelles|La Digue Island": "https://commons.wikimedia.org/wiki/File%3ALa_Digue_island%2C_Seychelles_%2839587412722%29.jpg",
    "Seychelles|Praslin Island": "https://commons.wikimedia.org/wiki/File%3APraslin_Island%2C_Anse_Possession%2C_November_2019.jpg",
    "Seychelles|Island Hopping": "https://commons.wikimedia.org/wiki/File%3AAride_Island_Seychelles.jpg",
    "Australia|Great Ocean Road": "https://commons.wikimedia.org/wiki/File%3AGreatOceanRoad.jpg",
    "Australia|Phillip Island Penguins": "https://commons.wikimedia.org/wiki/File%3AAustralia_-_Phillip_Island_-_Penguin_%28Eudyptula_minor%29.jpg",
    "Australia|Blue Mountains": "https://commons.wikimedia.org/wiki/File%3AThe_Blue_Mountains%2C_Australia.jpg",
    "Australia|Reef Cruise": "https://commons.wikimedia.org/wiki/File%3A.00_0975_Ningaloo_Reef_%28Australia%29_-_Surf_on_the_coral_reef.jpg",
    "New Zealand|Queenstown Bungy": "https://commons.wikimedia.org/wiki/File%3ABungy_jumping_from_the_Kawarau_Bridge_near_Queenstown_1988_%2810805217116%29.jpg",
    "New Zealand|Hobbiton": "https://commons.wikimedia.org/wiki/File%3AHobbiton%2C_New_Zealand.jpg",
    "New Zealand|Rotorua Geothermal": "https://commons.wikimedia.org/wiki/File%3ARotoruaHotSpringNZ.jpg",
    "New Zealand|TSS Earnslaw Cruise": "https://commons.wikimedia.org/wiki/File%3ATSS_Earnslaw_%289419362424%29.jpg",
    "Hong Kong & Macau|Disneyland": "https://commons.wikimedia.org/wiki/File%3AHong_Kong_Disneyland_%2823988762030%29.jpg",
    "Hong Kong & Macau|Ngong Ping 360": "https://commons.wikimedia.org/wiki/File%3ANgong_ping_360.JPG",
    "Hong Kong & Macau|Macau Venetian": "https://commons.wikimedia.org/wiki/File%3AMY-45-82_Hong_Kong-Zhuhai-Macau_Bridge_Macau_Port_to_The_Venetian_Macao_shuttle_bus_17-02-2026%281%29.jpg",
    "Hong Kong & Macau|Star Ferry": "https://commons.wikimedia.org/wiki/File%3AStar_Ferry_Hong_Kong._%2814143932945%29.jpg",
    "Kenya Safari|Hot Air Balloon Safari": "https://commons.wikimedia.org/wiki/File%3AHot_Air_Balloon.jpg",
    "Kenya Safari|Lake Nakuru": "https://commons.wikimedia.org/wiki/File%3ALake_Nakuru_in_Kenya.jpg",
    "Kenya Safari|Amboseli & Kilimanjaro Views": "https://commons.wikimedia.org/wiki/File%3AMt_Kilimanjaro_view_from_Amboseli.jpg",
    "Kenya Safari|Maasai Village": "https://commons.wikimedia.org/wiki/File%3AMaasai_Village_%2832%29.jpg",
    "Azerbaijan (Baku)|Gobustan": "https://commons.wikimedia.org/wiki/File%3AGobustan.jpg",
    "Azerbaijan (Baku)|Old City Icheri Sheher": "https://commons.wikimedia.org/wiki/File%3AOld_City_%28Baku%29.JPG",
    "Azerbaijan (Baku)|Shahdag Cable Car": "https://commons.wikimedia.org/wiki/File%3AShahdag.jpg",
    "Azerbaijan (Baku)|Yanar Dag Fire Mountain": "https://commons.wikimedia.org/wiki/File%3AFire_Mountains.jpg",
    "USA - East Coast|Times Square": "https://commons.wikimedia.org/wiki/File%3ATimes_Square_at_night-_Manhattan%2C_New_York_City%2C_United_States_of_America_%289867925666%29.jpg",
    "USA - East Coast|Niagara Falls": "https://commons.wikimedia.org/wiki/File%3ANiagara_Falls_%28_American_Falls_%29.jpg",
    "USA - East Coast|White House Tour": "https://commons.wikimedia.org/wiki/File%3AVisitors_tour_the_White_House_in_Washington%2C_D.C.jpg",
    "USA - East Coast|Empire State Building": "https://commons.wikimedia.org/wiki/File%3AEmpire_State_Building_%281%29.JPG",
}


def photo_url(destination, spot=""):
    """Return a direct photo URL for template fallbacks without making API requests."""
    source = SOURCES.get(f"{destination}|{spot}") or SOURCES.get(f"{destination}|")
    if not source:
        return ""
    filename = unquote(urlparse(source).path).split("/File:", 1)[1].replace(" ", "_")
    digest = hashlib.md5(filename.encode("utf-8")).hexdigest()
    return (f"https://upload.wikimedia.org/wikipedia/commons/{digest[0]}/{digest[:2]}/"
            + quote(filename, safe=""))
